version: "2"

run:
  timeout: 30m
  tests: true
  build-tags: []

linters:
  enable:
    # Enabled by default
    - errcheck      # Check for unchecked errors
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - unused        # Check for unused code

    # Additional recommended linters
    - misspell      # Find commonly misspelled English words
    - unconvert     # Remove unnecessary type conversions
    - gocyclo       # Check cyclomatic complexity
    - gocritic      # Comprehensive Go linter

  disable:
    - depguard      # Can be too restrictive for general use
    - unparam       # Too many false positives for functions keeping params for consistency

  exclusions:
    rules:
      # Common false positives - fmt print functions and deferred cleanup don't need error checking
      - text: "Error return value of .((os\\.RemoveAll|fmt\\.(Fprint|Fprintf|Fprintln)|.*\\.Close|.*\\.Write|.*\\.Flush)). is not checked"
        linters: [errcheck]

      # Exclude some linters from running on tests files
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec

  settings:
    gocyclo:
      min-complexity: 15

    misspell:
      locale: US

    revive:
      rules:
        - name: exported
          disabled: false
        - name: package-comments
          disabled: true

formatters:
  enable:
    - gofmt         # Check whether code was gofmt-ed
    - goimports     # Check import statements are formatted

issues:
  # Maximum issues count per linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0
