#!/bin/bash -eu

ddir=/tmp/$USER/gojekyll-compare
basename=$(basename $1)

./scripts/gojekyll build -s $1 -d $ddir/$basename.go
(cd $1 && bundle exec jekyll build -d $ddir/$basename.jekyll)
ksdiff $ddir/$basename.jekyll $ddir/$basename.go
